;<KHeader>
;+=========================================================================
;I  Project Name: EApiDK Embedded Application Development Kit
;+=========================================================================
;I  $HeadURL: https://eapidk.svn.sourceforge.net/svnroot/eapidk/trunk/include/masm/EeeP.inc $
;+=========================================================================
;I   Copyright: Copyright (c) 2002-2009, Kontron Embedded Modules GmbH
;I      Author: John Kearney,                  John.Kearney@kontron.com
;I
;I     License: All rights reserved. This program and the accompanying 
;I              materials are licensed and made available under the 
;I              terms and conditions of the BSD License which 
;I              accompanies this distribution. The full text of the 
;I              license may be found at 
;I              http://opensource.org/licenses/bsd-license.php
;I              
;I              THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "
;I              AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS OF 
;I              ANY KIND, EITHER EXPRESS OR IMPLIED.
;I
;I Description: Auto Created for EApi.inc
;I
;+-------------------------------------------------------------------------
;I
;I  File Name            : EeeP.inc
;I  File Location        : include\masm
;I  Last committed       : $Revision: 38 $
;I  Last changed by      : $Author: dethrophes $
;I  Last changed date    : $Date: 2010-01-26 07:48:22 +0100 (Di, 26 Jan 2010) $
;I  ID                   : $Id: EeeP.inc 38 2010-01-26 06:48:22Z dethrophes $
;I
;+=========================================================================
;</KHeader>
IFNDEF __EEEP_INC__
__EEEP_INC__ TEXTEQU <>

        include <EeePConv.inc>

ENDIF  __EEEP_INC__
