#ifndef _SEMA_DEFINE_H
#define _SEMA_DEFINE_H

/* SEMA LENGTH DEFINES */
#define MAX_BUFFER_LENGTH			1024
#define MAX_BUFFER_LENGTH_LARGE		10240


#define SEMA_AGENT "SEMA_AGENT"
#define SEMA_EAPI  "REMOTE EAPI"
#define SEMA_AUTORECOVERY "AUTORECOVERY"
#define SEMA_MAINTENANCE "MAINTENANCE"
#define SEMA_BOARDINFORMATION "BOARDINFO"
#define SEMA_POWERCONSUMPUTION "POWER"
#define SEMA_HEALTHCHECK "HEALTH"
#define SEMA_HEARTBEAT "HEARTBEAT"

#define SEMA_MQ_COMMAND_WDSTART		1
#define SEMA_MQ_COMMAND_WDSTOP		2

typedef enum _SEMA_RETURN_CODE{
	 SEMA_OK=				1,
	 SEMA_FAIL=			0,
	 SEMA_NO_RESPONSE=	-1,
	 SEMA_SYSTEM_BUSY=	-2
}SEMA_RETURN_CODE;


typedef enum _SEMA_SERVICE_STATE{
	SEMA_SERVICE_ON = 0 ,
	SEMA_SERVICE_BUSY = 1,
	SEMA_SERVICE_STOP = 2,
	SEMA_SERVICE_NOT_FOUND = 3,
	SEMA_SERVICE_INITIATING = 4
}SEMA_SERVICE_STATE; 

#define HASH_LEN 16

typedef enum _IPVERSION{
	IP_V4 = 0,
	IP_V6 = 1
}IP_Version;


/*EAPI Extend IDS */

/*SEMA extend EAPI ID for SemaEApiBoardGetStringA*/
#define SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE	EAPI_UINT32_C(0x10000)
/* Boot version String*/
#define SEMA_EAPI_ID_BOARD_BOOT_VERSION_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+1
/* Chipset ID String*/
#define SEMA_EAPI_ID_BOARD_CHIPSET_ID_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+2
/* Restart Event String*/
#define SEMA_EAPI_ID_BOARD_RESTART_EVENT_STR	SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+3
/* Device ID string */
#define SEMA_EAPI_ID_BOARD_DEVICE_ID_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+4
/* Device BMC Firmware application string */
#define SEMA_EAPI_ID_BOARD_APPLICATION_VERSION_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+5
/* Last Repair Date string */
#define SEMA_EAPI_ID_BOARD_REPAIR_DATE_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+6
/* Manufacture date string */
#define SEMA_EAPI_ID_BOARD_MANUFACTURE_DATE_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+7
/* MAC address on module string */
#define SEMA_EAPI_ID_BOARD_MAC_STRING		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+8
/* 2nd HW revision string */
#define SEMA_EAPI_ID_BOARD_2ND_HW_REVISION_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+9
/* 2nd HW serial string */
#define SEMA_EAPI_ID_BOARD_2ND_SERIAL_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+10
/* Platform ID*/
//#define SEMA_EAPI_ID_BOARD_PLATFORM_TYPE_STR		SEMA_EAPI_ID_BOARD_STR_EXTENDED_BASE+11



/*SEMA extend EAPI ID for SemaEApiBoardGetValue*/
#define SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE  EAPI_UINT32_C(0x30000) 
/* Chipset ID*/
#define SEMA_EAPI_ID_BOARD_CHIPSET_ID			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+1
/* SEMA Capabilities */
#define SEMA_EAPI_ID_BOARD_CAPABILITIES			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+2
/* Total Up Time */
#define SEMA_EAPI_ID_BOARD_TOTAL_UP_TIME		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+3
/* Power Cycles */
#define SEMA_EAPI_ID_BOARD_POWER_CYCLE			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+4
/* Restart Event */
#define SEMA_EAPI_ID_BOARD_RESTART_EVENT		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+5
/* Main Power Current*/
#define SEMA_EAPI_ID_BOARD_MAIN_CURRENT			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+6
/* Board Min Temperature*/
#define SEMA_EAPI_ID_BOARD_SYSTEM_MIN_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+7
/* Board Max Temperature*/
#define SEMA_EAPI_ID_BOARD_SYSTEM_MAX_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+8
/* Board Startup Temperature*/
#define SEMA_EAPI_ID_BOARD_SYSTEM_STARTUP_TEMP			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+9
/* CPU Min Temperature*/
#define SEMA_EAPI_ID_BOARD_CPU_MIN_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+10
/* CPU Max Temperature*/
#define SEMA_EAPI_ID_BOARD_CPU_MAX_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+11
/* CPU Startup Temperature*/
#define SEMA_EAPI_ID_BOARD_CPU_STARTUP_TEMP			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+12
/* Powerup time */
#define SEMA_EAPI_ID_BOARD_POWER_UP_TIME			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+13
/* GFX-VCore*/
#define SEMA_EAPI_ID_HWMON_VOLTAGE_GFX_VCORE		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+15
/* 1.05 V*/
#define SEMA_EAPI_ID_HWMON_VOLTAGE_1V05		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+16
/* 1.5 V*/
#define SEMA_EAPI_ID_HWMON_VOLTAGE_1V5		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+17
/* Vin*/
#define SEMA_EAPI_ID_HWMON_VOLTAGE_VIN		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+18
/* FAN IDs */
#define SEMA_EAPI_ID_HWMON_FAN_SYSTEM_2   	    SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+19 /* System FAN ID 2 */
#define SEMA_EAPI_ID_HWMON_FAN_SYSTEM_3   	    SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+20 /* System FAN ID 3 */

#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN0      EAPI_UINT32_C(0x21004) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN1    EAPI_UINT32_C(0x21008) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN2  EAPI_UINT32_C(0x2100C) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN3       EAPI_UINT32_C(0x21010) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN4   EAPI_UINT32_C(0x21014) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN5      EAPI_UINT32_C(0x21018) /* millivolts */
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN6    EAPI_UINT32_C(0x2101C) /* millivolts */

#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN7		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+15
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN8		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+16
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN9		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+17
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN10	SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+18
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN11		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+21
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN12	SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+22
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN13	SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+23
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN14	SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+24
#define SEMA_EAPI_ID_HWMON_VOLTAGE_AIN15	SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+25

/* SEMA Capabilities EX */
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_EX		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+26

/* Board 2nd Min Temperature*/
#define SEMA_EAPI_ID_BOARD_2ND_SYSTEM_MIN_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+27
/* Board 2nd Max Temperature*/
#define SEMA_EAPI_ID_BOARD_2ND_SYSTEM_MAX_TEMP				SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+28
/* Board 2nd Startup Temperature*/
#define SEMA_EAPI_ID_BOARD_2ND_SYSTEM_STARTUP_TEMP			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+29

/* Board 2nd System Temperature*/
#define	SEMA_EAPI_ID_BOARD_2ND_SYSTEM_TEMP		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+30

/*Platform Spec Version*/
//#define SEMA_EAPI_ID_BOARD_PLATFORM_SPEC_VER   	    SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+33
/*BMC*/
#define SEMA_EAPI_ID_BOARD_BMC_FLAG			SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+31
#define SEMA_EAPI_ID_BOARD_BMC_STATUS		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+32

#define SEMA_EAPI_ID_BOARD_IO_CURRENT          SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+33

/* SEMA Capabilities 2~7 */
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_2		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+34
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_3		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+35
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_4		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+36
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_5		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+37
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_6		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+38
#define SEMA_EAPI_ID_BOARD_CAPABILITIES_7		SEMA_EAPI_ID_BOARD_VALUE_EXTENDED_BASE+39

/* SEMA extend EAPI ID for SemaEApiCPUGetString */
#define SEMA_EAPI_ID_CPU_GET_STRING_EXTENDED_BASE   EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_MODEL_NAME             SEMA_EAPI_ID_CPU_GET_STRING_EXTENDED_BASE+1

/* SEMA extend EAPI ID for SemaEApiCPUGetValue */
#define SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE    EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_CPU_FREQUENCY                  SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+1
#define SEMA_EAPI_ID_CPU_OPERATION_MODE             SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+2
#define SEMA_EAPI_ID_CPU_COUNT                      SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+3
#define SEMA_EAPI_ID_CPU_CORE_COUNT                 SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+4
#define SEMA_EAPI_ID_CPU_L1_CACHE                   SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+5
#define SEMA_EAPI_ID_CPU_L2_CACHE                   SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+6
#define SEMA_EAPI_ID_CPU_L3_CACHE                   SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+7
#define SEMA_EAPI_ID_CPU_USAGE                      SEMA_EAPI_ID_CPU_GET_VALUE_EXTENDED_BASE+8
/* SEMA Operation Mode ID for SemaEApiCPUGetValue SEMA_EAPI_ID_CPU_OPERATION_MODE */
#define SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE   EAPI_UINT32_C(0x1000)
#define CPU_OPERATION_MODE_UNSUPPORTED					SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE
#define CPU_OPERATION_MODE_UNKNOWN						SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+1
#define CPU_HIGH_PERFORMANCE_MODE						SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+2
#define CPU_POWERSAVE_MODE								SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+3
#define CPU_ONDEMAND_MODE								SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+4
#define CPU_CONSERVATIVE_MODE							SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+5
#define CPU_USERSPACE_MODE								SEMA_EAPI_ID_CPU_OPERATION_MODE_EXTENDED_BASE+6
/* SEMA extend EAPI ID for SemaEApiCPUSetValue */
#define SEMA_EAPI_ID_CPU_SET_VALUE_EXTENDED_BASE    EAPI_UINT32_C(0x1000)
#define CPU_OPERATION_MODE_SET_ERROR                SEMA_EAPI_ID_CPU_SET_VALUE_EXTENDED_BASE+2
#define CPU_OPERATION_MODE_SET_SUCCESS              SEMA_EAPI_ID_CPU_SET_VALUE_EXTENDED_BASE+3


/* SEMA extend EAPI ID for SemaEApiMemoryGetValue */
#define SEMA_EAPI_ID_MEMORY_GET_VALUE_EXTENDED_BASE     EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_MEMORY_FREQUENCY                   SEMA_EAPI_ID_MEMORY_GET_VALUE_EXTENDED_BASE+1
#define SEMA_EAPI_ID_MEMORY_TOTAL                       SEMA_EAPI_ID_MEMORY_GET_VALUE_EXTENDED_BASE+2
#define SEMA_EAPI_ID_MEMORY_FREE                        SEMA_EAPI_ID_MEMORY_GET_VALUE_EXTENDED_BASE+3

/* SEMA extend EAPI ID for SemaEApiNetworkGetString */
#define SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE   EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_NETWORK_ADAPTER_NAME               SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE+1
#define SEMA_EAPI_ID_NETWORK_IP_ADDRESS                 SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE+2
#define SEMA_EAPI_ID_NETWORK_SUBMASK                    SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE+3
#define SEMA_EAPI_ID_NETWORK_GATEWAY                    SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE+4
#define SEMA_EAPI_ID_NETWORK_MAC                        SEMA_EAPI_ID_NETWORK_GET_STRING_EXTENDED_BASE+5

/* SEMA extend EAPI ID for SemaEApiNetworkGetValue */
#define SEMA_EAPI_ID_NETWORK_GET_VALUE_EXTENDED_BASE    EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_NETWORK_TX                         SEMA_EAPI_ID_NETWORK_GET_VALUE_EXTENDED_BASE+1
#define SEMA_EAPI_ID_NETWORK_RX                         SEMA_EAPI_ID_NETWORK_GET_VALUE_EXTENDED_BASE+2

/* SEMA Device ID for SemaEApiNetworkGetValue */
#define SEMA_EAPI_ID_NETWORK_DEVICE_ID_EXTENDED_BASE    EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_NETWORK_ETH0                       SEMA_EAPI_ID_NETWORK_DEVICE_ID_EXTENDED_BASE+1
#define SEMA_EAPI_ID_NETWORK_ETH1                       SEMA_EAPI_ID_NETWORK_DEVICE_ID_EXTENDED_BASE+2
#define SEMA_EAPI_ID_NETWORK_ETH2                       SEMA_EAPI_ID_NETWORK_DEVICE_ID_EXTENDED_BASE+3
#define SEMA_EAPI_ID_NETWORK_ETH3                       SEMA_EAPI_ID_NETWORK_DEVICE_ID_EXTENDED_BASE+4

/* SEMA Device ID for SemaEApiSystemBootSet */
#define SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE    EAPI_UINT32_C(0x1000)
#define SEMA_EAPI_ID_SYSTEM_BOOT_POWER_UP                   SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+1
#define SEMA_EAPI_ID_SYSTEM_BOOT_SW_SHUTDOWN                     SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+2
#define SEMA_EAPI_ID_SYSTEM_BOOT_SW_RESTART                      SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+3
#define SEMA_EAPI_ID_SYSTEM_BOOT_HW_SHUTDOWN                     SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+4
#define SEMA_EAPI_ID_SYSTEM_BOOT_HW_RESTART                      SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+5
#define SEMA_EAPI_ID_SYSTEM_BOOT_SW_SUSPEND					SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+6
#define SEMA_EAPI_ID_SYSTEM_BOOT_SW_HIBERNATE				SEMA_EAPI_ID_SYSTEM_BOOT_DEVICE_ID_EXTENDED_BASE+7

/* SEMA EAPI ID for update status */
#define SEMA_EAPI_FW_UPDATE_ID_EXTENDED_BASE    		EAPI_UINT32_C(0x1000)
#define SEMA_FW_UPDATE_RUNNING							SEMA_EAPI_FW_UPDATE_ID_EXTENDED_BASE+1
#define SEMA_FW_UPDATE_SUCCESS							SEMA_EAPI_FW_UPDATE_ID_EXTENDED_BASE+2
#define SEMA_FW_UPDATE_UNSUPPORTED						SEMA_EAPI_FW_UPDATE_ID_EXTENDED_BASE+3
#define SEMA_FW_UPDATE_ERROR							SEMA_EAPI_FW_UPDATE_ID_EXTENDED_BASE+4

/* FAN IDs */
#define SEMA_EAPI_ID_FAN_CPU       		EAPI_UINT32_C(0) /* CPU FAN ID */
#define SEMA_EAPI_ID_FAN_SYSTEM_1   	    EAPI_UINT32_C(1) /* System FAN 1 ID */
#define SEMA_EAPI_ID_FAN_SYSTEM_2   	    EAPI_UINT32_C(2) /* System FAN 2 ID */
#define SEMA_EAPI_ID_FAN_SYSTEM_3   	    EAPI_UINT32_C(3) /* System FAN 3 ID */

/* SM-Bus IDs*/
#define	SEMA_EAPI_ID_SMBUS_B		EAPI_UINT32_C( 0 ) /* Byte data */
#define	SEMA_EAPI_ID_SMBUS_BB		EAPI_UINT32_C( 1 ) /* Byte command and byte data */
#define	SEMA_EAPI_ID_SMBUS_BW		EAPI_UINT32_C( 2 ) /* Byte command and word data */

#define	SEMA_EAPI_ID_SMBUS_MODE		EAPI_UINT32_C( 0 ) /* SM-bus mode */
#define	SEMA_EAPI_ID_SMBUS_I2C_MODE	EAPI_UINT32_C( 1 ) /* SM-bus I2C mode */
// #define	SEMA_EAPI_ID_SMBUS_PEC_MODE	EAPI_UINT32_C( 2 ) /*SM-bus + PEC byte mode */

#endif //_SEMA_DEFINE_H
